# Generated by Django 4.0.4 on 2022-05-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryleaderboard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='slidingpuzzleleaderboard',
            name='id',
        ),
        migrations.AddField(
            model_name='countryleaderboard',
            name='EntryId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidingpuzzleleaderboard',
            name='EntryId',
            field=models.AutoField(default=23, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
